In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import requests
from scipy.signal import find_peaks
from matplotlib.ticker import MultipleLocator
import math

pd.set_option('display.width', 5000)          # total width before wrapping
pd.set_option('display.max_columns', None)

In [2]:
all_plays = pd.read_csv('player_play_routes.csv')
all_plays = all_plays[all_plays['play_type'] == 'play_type_pass']
unique_plays = all_plays[['game_id', 'gsis_play_id']].drop_duplicates()
unique_plays

C:\Users\benjamin.harris-mye\AppData\Local\Temp\ipykernel_20224\3024728082.py:1: DtypeWarning: Columns (0: drop_back_type, 1: drop_back_time, 2: pass_location_type, 3: shift_since_lineset, 4: pass_defended, 5: recovered_fumble, 6: caused_forced_fumble, 7: is_called_pass) have mixed types. Specify dtype option on import or set low_memory=False.
  all_plays = pd.read_csv('player_play_routes.csv')

            game_id  gsis_play_id
0        2017081252          1889
2        2025102600          3229
3        2019082963          1657
4        2025102600          3017
6        2017110506          1280
...             ...           ...
1103556  2024102701          1961
1105379  2017123107           320
1105717  2021120503          3529
1106753  2025010500          3221
1107528  2024091500          3935

[216053 rows x 2 columns]

In [3]:
# Set authorization token - replace with your own token
auth_token = "NGS AKIAY5YRP3ZL7RRDSWVW:kuV9ds/mQjRREPhFXW9lz/Sff2s="

# Pull the plays data (replace with your own path) - this should include position info, nfl ids, game ids, and play ids at a minimum. We will use the game and play ids to pull tracking data
play_info = all_plays # -> Use a SQL query to pull play IDs

# Function to pull tracking data for a given player and play
def pull_tracking_data(game_id, play_id):

    # Testing - Use these values if you want to run anything within the function directly
    # game_id = 2025090400
    # play_id = 71

    url = f"https://api.ngs.nfl.com/tracking/game/play?gameId={game_id}&gsisPlayId={play_id}"
    
    headers = {
        "Authorization": auth_token
    }
    
    response = requests.get(url, headers=headers)
    res_json = response.json()
    # print(res_json)

    # Extract the home and away tracking data
    home_tracking = pd.json_normalize(res_json['homeTrackingData']).assign(game_id=game_id, gsis_play_id=play_id)
    away_tracking = pd.json_normalize(res_json['awayTrackingData']).assign(game_id=game_id, gsis_play_id=play_id)
    # print(away_tracking)

    # Merge the tracking data
    tracking = pd.concat([home_tracking, away_tracking], ignore_index=True)

    # Unnest the playerTrackingData column
    if 'playerTrackingData' in tracking.columns:
        player_tracking_list = []
        for idx, row in tracking.iterrows():
            if isinstance(row['playerTrackingData'], list):
                player_df = pd.json_normalize(row['playerTrackingData'])
                # Add all other columns from the parent row
                for col in tracking.columns:
                    if col != 'playerTrackingData':
                        player_df[col] = row[col]
                player_tracking_list.append(player_df)
        
        if player_tracking_list:
            tracking = pd.concat(player_tracking_list, ignore_index=True)

    # print(tracking)
    # Filter to what we need - expand or contact this list as necessary
    tracking = tracking[['time', 'a', 'dir', 'dis','s', 'event', 'x', 'y', 'nflId', 'displayName', 'position', 'positionGroup', 'game_id', 'gsis_play_id']]

    numeric_cols = ['a', 'dir', 'dis', 's', 'x', 'y', 'game_id', 'gsis_play_id', 'nflId']  # List your numeric columns
    for col in numeric_cols:
        tracking[col] = pd.to_numeric(tracking[col], errors = 'coerce')  # Use 'coerce' to turn invalids to NaN

    # Merge with play_info to get player positions (ngs_position) and other details
    tracking_df_merged = tracking.merge(
        play_info,
        left_on=['game_id', 'gsis_play_id', 'nflId'],
        right_on=['game_id', 'gsis_play_id', 'nfl_id'],
        how='left'
    )

    # Convert time to datetime
    tracking_df_merged['time'] = pd.to_datetime(tracking_df_merged['time'], format="%Y-%m-%dT%H:%M:%S.%f", utc=True, errors='coerce')

    # Create frame_id (group by time) - this is helpful for frame identification
    tracking_df_merged['frame_id'] = (
        tracking_df_merged.groupby('time')
        .ngroup()
        .astype(str)
    )
    tracking_df_merged['frame_id'] = (
        tracking_df_merged['game_id'].astype(str) + "-" +
        tracking_df_merged['gsis_play_id'].astype(str) + "-" +
        tracking_df_merged['frame_id'].astype(str).str.zfill(3)
    )

    # ***OPTIONAL: In this section, you can cut for specific frames (i.e. post ball_snap) using the events column***

    return tracking_df_merged

# tracking_df_merged will be all your tracking data for a particular play. to get multiple plays and games, you would loop through games ids as well and then nest the play id loop within it (see below)

In [35]:
tracking_data = pd.DataFrame()

for _, row in unique_plays.iterrows():
    if row['game_id'] == 2025090400:
        # print('ere')
        print(row['game_id'], row['gsis_play_id'])
        tracking_data_pulled = pull_tracking_data(game_id=row['game_id'], play_id=row['gsis_play_id'])
        tracking_data = pd.concat([tracking_data, tracking_data_pulled], ignore_index=True)

tracking_data = tracking_data[(tracking_data['offense_play'] == True) 
                                & (tracking_data['was_running_route'] == True)
                                # & (tracking_data['route'] != 'GO')
                                # & (tracking_data['pass_blocking'] != 'True')
                              ]

tracking_data

2025090400 1933
2025090400 2164
2025090400 3451
2025090400 3643
2025090400 3724
2025090400 3671
2025090400 3701
2025090400 1958
2025090400 1695
2025090400 330
2025090400 1995
2025090400 717
2025090400 2984
2025090400 3606
2025090400 3266
2025090400 2609
2025090400 2498
2025090400 2867
2025090400 1647
2025090400 1043
2025090400 1725
2025090400 3219
2025090400 3027
2025090400 1326
2025090400 1093
2025090400 141
2025090400 778
2025090400 2352
2025090400 2939
2025090400 3425
2025090400 2189
2025090400 1508
2025090400 1301
2025090400 2586
2025090400 2020
2025090400 1603
2025090400 2892
2025090400 426
2025090400 3364
2025090400 1485
2025090400 842
2025090400 1462
2025090400 3772
2025090400 1897
2025090400 3296
2025090400 1068
2025090400 3824
2025090400 1672
2025090400 3191
2025090400 2780
2025090400 996
2025090400 3562
2025090400 648
2025090400 3747
2025090400 2219
2025090400 188

                                   time     a     dir   dis     s        event       x      y  nflId     displayName position_x positionGroup     game_id  gsis_play_id   nfl_id  season season_type  week  game_key  team_id  opponent_team_id team_abbr     esb_id     gsis_id     player_name first_name last_name short_name position_y position_group  jersey_number       play_type  quarter  down  yards_to_go  possession_team_id  pass_yards  rec_yards  rush_yards  yards_after_catch  x_at_snap  y_at_snap was_running_route playing_high_safety lined_up_as_qb playtime_play no_play exclude_leader ball_carrier tackler interceptor participant target offense_play defense_play st_play scoring_play  scramble_yards  in_play_dist  max_speed  x_ball_at_snap  y_ball_at_snap redzone_play offense_formation  defenders_in_the_box drop_back_type  drop_back_distance drop_back_time  avg_separation_to_qb  cushion receiver_location_type  lined_up_in_the_box blitzing  depth_from_los_at_snap pass_location_type  defender_location_type left_or_right_of_center  separation_to_qb  caused_pressure  nearest_teammate_id  nearest_teammate_distance stat_ids play_direction run_stuff_eligible in_motion_at_ball_snap shift_since_lineset  score_differential  yards count_performance ngs_position ngs_position_group  pressure_caused_turnover pass_defended  hurried_qb  time_to_qb_hurry  player_get_off qb_kneel  max_speed_until_pass_arrival  max_speed_until_pass_arrival_first_second  max_speed_until_pass_arrival_first_two_seconds  max_speed_until_pass_arrival_first_three_seconds  x_at_end_of_play  y_at_end_of_play  distance_from_lineset_to_snap  return_yards recovered_fumble fumble fumble_lost caused_forced_fumble  caused_pressure_at_pass_forward is_called_pass  time_to_pressure pass_blocking  missed_tackles_forced motion_since_lineset route             frame_id
3504   2025-09-05 01:42:43.200000+00:00  1.05  336.73  0.01  0.17          NaN   69.86  42.20  52425     CeeDee Lamb         WR            WR  2025090400          1933  52425.0  2025.0         REG   1.0   59843.0   1200.0            3700.0       DAL  LAM138457  00-0036358     CeeDee Lamb   Cedarian      Lamb     C.Lamb         WR             WR           88.0  play_type_pass      2.0   1.0         10.0              1200.0         NaN        NaN         NaN                NaN      69.79      42.21              True               False          False          True   False          False        False   False       False        True  False         True        False   False        False             NaN         31.32  15.913636           69.57           29.84        False           SHOTGUN                   6.0            NaN                 NaN            NaN                   NaN     7.44             RIGHT_WIDE                  NaN    False                    0.79                NaN                     NaN                   RIGHT               NaN              NaN              54594.0                   8.984035       {}           left              False                  False               False                -4.0    NaN              True           WR                 WR                       NaN           NaN         NaN               NaN             NaN    False                     15.913636                                   9.245455                                       15.320455                                         15.913636             39.25             39.79                           0.29           NaN              NaN    NaN         NaN                  NaN                              NaN           True               NaN         False                    NaN                False    GO  2025090400-1933-000
3505   2025-09-05 01:42:43.300000+00:00  0.59  339.49  0.02  0.19          NaN   69.86  42.22  52425     CeeDee Lamb         WR            WR  2025090400          1933  52425.0  2025.0         REG   1.0   59843.0   1200.0            3700.0       DAL  LAM138457  00-0036358     CeeDee Lamb   Cedarian      Lamb     C.Lamb         WR             WR           88.0  play_type_pass      2.0   1.0         10.0              1200.0         NaN        NaN         NaN                NaN      69.79      42.21              True               False          False          True   False          False        False   False       False        True  False         True        False   False        False             NaN         31.32  15.913636           69.57           29.84        False           SHOTGUN                   6.0            NaN                 NaN            NaN                   NaN     7.44             RIGHT_WIDE                  NaN    False                    0.79                NaN                     NaN                   RIGHT               NaN              NaN              54594.0                   8.984035       {}           left              False                  False               False                -4.0    NaN              True           WR                 WR                       NaN           NaN         NaN               NaN             NaN    False                     15.913636                                   9.245455                                       15.320455                                         15.913636             39.25             39.79                           0.29           NaN              NaN    NaN         NaN                  NaN                              NaN           True               NaN         False                    NaN                False    GO  2025090400-1933-001
3506   2025-09-05 01:42:43.400000+00:00  0.27  351.53  0.02  0.21          NaN   69.85  42.24  52425     CeeDee Lamb         WR            WR  2025090400          1933  52425.0  2025.0         REG   1.0   59843.0   1200.0            3700.0       DAL  LAM138457  00-0036358     CeeDee Lamb   Cedarian      Lamb     C.Lamb         WR             WR           88.0  play_type_pass      2.0   1.0         10.0              1200.0         NaN        NaN         NaN                NaN      69.79      42.21              True               False          False          True   False          False        False   False       False        True  False         True        False   False        False             NaN         31.32  15.913636           69.57           29.84        False           SHOTGUN                   6.0            NaN                 NaN            NaN                   NaN     7.44             RIGHT_WIDE                  NaN    False                    0.79                NaN                     NaN                   RIGHT               NaN              NaN              54594.0                   8.984035       {}           left              False                  False               False                -4.0    NaN              True           WR                 WR                       NaN           NaN         NaN               NaN             NaN    False                     15.913636                                   9.245455                                       15.320455                                         15.913636             39.25             39.79                           0.29           NaN              NaN    NaN         NaN                  NaN                              NaN           True               NaN         False                    NaN                False    GO  2025090400-1933-002
3507   2025-09-05 01:42:43.500000+00:00  0.23  359.94  0.02  0.20          NaN   69.85  42.26  52425     CeeDee Lamb         WR            WR  2025090400          1933  52425.0  2025.0         REG   1.0   59843.0   1200.0            3700.0       DAL  LAM138457  00-0036358     CeeDee Lamb   Cedarian      Lamb     C.Lamb         WR             WR           88.0  play_type_pass      2.0   1.0         10.0              1200.0         NaN        NaN         NaN                NaN      69.79      42.21              True               False          False          True   False          False        False   False       False        True  False         True        False   False        False             NaN         31.32  15.913636           69.57           29.84        False           SHOTGUN                   6.0            NaN                 NaN            NaN                   NaN     7.44             RIGHT_WIDE                  NaN    False                    0.79                NaN                     NaN                   RIGHT               NaN              NaN              54594.0                   8.984035       {}           left              False                  False               False                -4.0    NaN              True           WR                 WR                       NaN           NaN         NaN               NaN             NaN    False                     15.913636                                   9.245455                                       15.320455                                         15.913636             39.25             39.79                           0.29           NaN              NaN    NaN         NaN                  NaN                              NaN           True               NaN         False                    NaN                False    GO  2025090400-1933-003
3508   2025-09-05 01:42:43.600000+00:00  0.07  338.08  0.02  0.20          NaN   69.84  42.28  52425     CeeDee Lamb         WR            WR  2025090400          1933  52425.0  2025.0         REG   1.0   59843.0   1200.0            3700.0       DAL  LAM138457  00-0036358     CeeDee Lamb   Cedarian      Lamb     C.Lamb         WR             WR           88.0  play_type_pass      2.0   1.0         10.0              1200.0         NaN        NaN         NaN                NaN      69.79      42.21              True               False          False          True   False          False        False   False       False        True  False         True        False   False        False             NaN         31.32  15.913636           69.57           29.84        False           SHOTGUN                   6.0            NaN                 NaN            NaN                   NaN     7.44             RIGHT_WIDE                  NaN    False                    0.79                NaN                     NaN                   RIGHT               NaN              NaN              54594.0                   8.984035       {}           left              False                  False               False                -4.0    NaN              True           WR                 WR                       NaN           NaN         NaN               NaN             NaN    False                     15.913636                                   9.245455                                       15.320455                                         15.913636             39.25             39.79                           0.29           NaN              NaN    NaN         NaN                  NaN                              NaN           True               NaN         False                    NaN                False    GO  2025090400-1933-004
...                                 ...   ...     ...   ...   ...          ...     ...    ...    ...             ...        ...           ...         ...           ...      ...     ...         ...   ...       ...      ...               ...       ...        ...         ...             ...        ...       ...        ...        ...            ...            ...             ...      ...   ...          ...                 ...         ...        ...         ...                ...        ...        ...               ...                 ...            ...           ...     ...            ...          ...     ...         ...         ...    ...          ...          ...     ...          ...             ...           ...        ...             ...             ...          ...               ...                   ...            ...                 ...            ...                   ...      ...                    ...                  ...      ...                     ...                ...                     ...                     ...               ...              ...                  ...                        ...      ...            ...                ...                    ...                 ...                 ...    ...               ...          ...                ...                       ...           ...         ...               ...             ...      ...                           ...                                        ...                                             ...                                               ...               ...               ...                            ...           ...              ...    ...         ...                  ...                              ...            ...               ...           ...                    ...                  ...   ...                  ...
369948 2025-09-05 00:29:54.800000+00:00  0.43  325.44  0.14  1.40          NaN  108.94   0.73  54517  George Pickens         WR            WR  2025090400           188  54517.0  2025.0         REG   1.0   59843.0   1200.0            3700.0       DAL  PIC576156  00-0037247  George Pickens     George   Pickens  G.Pickens         WR             WR            3.0  play_type_pass      1.0   3.0          1.0              1200.0         NaN        NaN         NaN                NaN      76.38      35.25              True               False          False          True   False          False        False   False       False        True  False         True        False   False        False             NaN         38.34  16.956818           76.92           24.22        False        SINGLEBACK                   7.0            NaN                 NaN            NaN                   NaN     8.37              LEFT_WIDE                  NaN    False                    0.62                NaN                     NaN                    LEFT               NaN              NaN              52425.0                  13.670937       {}          right              False                  False               False                 0.0    NaN              True           WR                 WR                       NaN           NaN         NaN               NaN             NaN    False                     16.956818                                   8.222727                                       14.768182                                         16.915909            106.23             14.71                           0.11           NaN              NaN    NaN         NaN                  NaN                              NaN           True               NaN         False                    NaN                False  POST   2025090400-188-334
369949 2025-09-05 00:29:54.900000+00:00  0.34  326.21  0.14  1.44          NaN  108.86   0.84  54517  George Pickens         WR            WR  2025090400           188  54517.0  2025.0         REG   1.0   59843.0   1200.0            3700.0       DAL  PIC576156  00-0037247  George Pickens     George   Pickens  G.Pickens         WR             WR            3.0  play_type_pass      1.0   3.0          1.0              1200.0         NaN        NaN         NaN                NaN      76.38      35.25              True               False          False          True   False          False        False   False       False        True  False         True        False   False        False             NaN         38.34  16.956818           76.92           24.22        False        SINGLEBACK                   7.0            NaN                 NaN            NaN                   NaN     8.37              LEFT_WIDE                  NaN    False                    0.62                NaN                     NaN                    LEFT               NaN              NaN              52425.0                  13.670937       {}          right              False                  False               False                 0.0    NaN              True           WR                 WR                       NaN           NaN         NaN               NaN             NaN    False                     16.956818                                   8.222727                                       14.768182                                         16.915909            106.23             14.71                           0.11           NaN              NaN    NaN         NaN                  NaN                              NaN           True               NaN         False                    NaN                False  POST   2025090400-188-335
369950        2025-09-05 00:29:55+00:00  0.31  327.90  0.15  1.48          NaN  108.78   0.97  54517  George Pickens         WR            WR  2025090400           188  54517.0  2025.0         REG   1.0   59843.0   1200.0            3700.0       DAL  PIC576156  00-0037247  George Pickens     George   Pickens  G.Pickens         WR             WR            3.0  play_type_pass      1.0   3.0          1.0              1200.0         NaN        NaN         NaN                NaN      76.38      35.25              True               False          False          True   False          False        False   False       False        True  False         True        False   False        False             NaN         38.34  16.956818           76.92           24.22        False        SINGLEBACK                   7.0            NaN                 NaN            NaN                   NaN     8.37              LEFT_WIDE                  NaN    False                    0.62                NaN                     NaN                    LEFT               NaN              NaN              52425.0                  13.670937       {}          right              False                  False               False                 0.0    NaN              True           WR                 WR                       NaN           NaN         NaN               NaN             NaN    False                     16.956818                                   8.222727                                       14.768182                                         16.915909            106.23             14.71                           0.11           NaN              NaN    NaN         NaN                  NaN                              NaN           True               NaN         False                    NaN                False  POST   2025090400-188-336

In [ ]:
# --- Per-route break-frame offset config ---
DEFAULT_BREAK_FRAME_OFFSET = 2

ROUTE_BREAK_FRAME_OFFSETS = {
    'SLANT': 1,
    'SCREEN': 1,
    'FLAT': 2,
    'OUT': 2,
    'HITCH': 4, 
    'CROSS': 2,
    'GO': 2,
    'ANGLE': 3,
    'IN': 3,
    'CORNER': 3,
    'POST': 3,
}


# Routes that structurally cannot have their break occur behind the LOS —
# for these, a candidate peak behind the LOS is disqualified outright,
# even if the player later crosses the LOS elsewhere in the play.
STRICT_LOS_ROUTES = {'OUT', 'POST', 'HITCH', 'IN', 'CORNER', 'SLANT', 'CROSS', 'ANGLE'}

def get_break_frame_offset(route, offsets=None, default=DEFAULT_BREAK_FRAME_OFFSET):
    """Look up the break-frame offset for a given route type.
    Falls back to `default` for unknown/missing routes."""
    offsets = offsets if offsets is not None else ROUTE_BREAK_FRAME_OFFSETS
    if route is None or pd.isna(route):
        return default
    return offsets.get(str(route).strip().upper(), default)

def shift_frame(frame_key: str, offset: int = 1) -> str:
    prefix, frame_str = frame_key.rsplit('-', 1)
    new_frame = int(frame_str) - offset
    padded_frame = str(new_frame).zfill(len(frame_str))
    return f"{prefix}-{padded_frame}"

def detect_route_break(df_player, min_angle_change=5, window=5, group_gap=10, 
                       enable_late_window_fallback=True, fallback_lookback=5, fallback_min_rise=.2,
                       min_speed_for_valid_dir=1.5,
                       press_cushion_threshold=3.0, press_frame_window=10, press_angle_multiplier=2.0,
                       route_offsets=None,
                       no_break_routes=('GO',),
                       strict_los_routes=None):
    df_player = df_player.sort_values('frame_id').reset_index(drop=True)

    # --- Resolve the break-frame offset for this player's route type ---
    route_type = df_player['route'].iloc[0] if 'route' in df_player.columns else None
    break_frame_offset = get_break_frame_offset(route_type, offsets=route_offsets)

    strict_los = strict_los_routes if strict_los_routes is not None else STRICT_LOS_ROUTES
    route_upper = str(route_type).strip().upper() if route_type is not None else None
    requires_strict_los = route_upper in strict_los

    # --- Route-type gate: some routes shouldn't produce a break at all
    # (e.g. GO routes are run in a straight line — any "break" detected
    # on one is noise, not a real cut). Skip detection entirely and
    # return empty results in the same shape as a normal "no break found" case.
    if route_type is not None and route_upper in no_break_routes:
        df_player['angle_change_rate'] = 0.0
        return df_player, np.array([]), [], [], []

    # Handle angle wrapping (0 to 360 deg)
    dir_rad = np.radians(df_player['dir'])
    sin_mean = np.sin(dir_rad).rolling(window, center=True, min_periods=1).mean()
    cos_mean = np.cos(dir_rad).rolling(window, center=True, min_periods=1).mean()
    smoothed_dir = np.degrees(np.arctan2(sin_mean, cos_mean)) % 360

    # Calculate absolute frame-to-frame change in heading
    angle_diff = np.abs(np.diff(smoothed_dir, prepend=smoothed_dir.iloc[0]))
    angle_diff = np.where(angle_diff > 180, 360 - angle_diff, angle_diff)

    df_player['angle_change_rate'] = angle_diff

    # --- Speed gate: at low speed, `dir` is noisy/poorly-defined, so treat any
    # angle change during low-speed frames as unreliable rather than a real cut.
    low_speed_mask = df_player['s'] < min_speed_for_valid_dir
    df_player['angle_change_rate'] = np.where(
        low_speed_mask, 0, df_player['angle_change_rate']
    )

    # --- Press gate: if the WR is pressed at the snap (cushion <= threshold),
    # early-route wiggle from fighting through contact can look like a break
    # even at real speed. Rather than zeroing it out (a real quick release
    # break can still happen), require a much larger angle change to count
    # as a break candidate during the first `press_frame_window` frames.
    is_pressed = df_player['cushion'].iloc[0] <= press_cushion_threshold
    press_frame_mask = df_player.index < press_frame_window

    # Find peaks in directional change rate
    peaks, properties = find_peaks(
        df_player['angle_change_rate'],
        height=1,
        distance=1
    )

    # Filter candidate peaks by total angle shift in surrounding window
    break_indices_candidates = [] 

    direction_mult = -1 if df_player['play_direction'].iloc[0] == 'left' else 1
    los_x_raw = df_player['x_ball_at_snap'].iloc[0]
    los_x = los_x_raw + 1 if df_player['play_direction'].iloc[0] == 'left' else los_x_raw - 1

    def _passes_los(x_val):
        if los_x is None:
            return True
        downfield_dist = direction_mult * (x_val - los_x)
        return round(downfield_dist) > 1

    def _required_angle_change(peak_idx):
        """Raise the bar for pressed WRs during the early-route window,
        since press wiggle can produce real-speed direction changes."""
        if is_pressed and press_frame_mask[peak_idx]:
            return min_angle_change * press_angle_multiplier
        return min_angle_change

    for peak in peaks:
        start_idx = max(0, peak - 1)
        end_idx = min(len(df_player) - 1, peak + 1)
        total_turn = np.sum(df_player['angle_change_rate'].iloc[start_idx:end_idx + 1])
        peak_frame = df_player['frame_id'].iloc[peak]
        peak_x = df_player['x'].iloc[peak]
        required_turn = _required_angle_change(peak)

        if not _passes_los(peak_x):
            # For routes that structurally can't break behind the LOS
            # (OUT, POST, HITCH, IN, CORNER, SLANT, CROSS), disqualify
            # this candidate outright — don't allow the "eventually
            # crosses the LOS" bypass to rescue it.
            if requires_strict_los:
                continue
            if _passes_los(df_player['x'].iloc[-1]):
                if total_turn >= required_turn:
                    break_indices_candidates.append({'peak': peak, 'frame': peak_frame, 'total_turn': total_turn})
            else:
                continue
        elif total_turn >= required_turn:
            break_indices_candidates.append({'peak': peak, 'frame': peak_frame, 'total_turn': total_turn})

    break_frames = []
    break_indices = []
    break_angles = []

    current_group = []
    for cand in break_indices_candidates:
        if not current_group or (cand['peak'] - current_group[-1]['peak']) <= group_gap:
            current_group.append(cand)
        else:
            best = max(current_group, key=lambda c: c['total_turn'])
            break_frames.append((shift_frame(best['frame'], offset=break_frame_offset), best['peak'], best['total_turn']))
            break_indices.append(best['peak'])
            break_angles.append(df_player['angle_change_rate'].iloc[best['peak']])
            current_group = [cand]

    if current_group:
        best = max(current_group, key=lambda c: c['total_turn'])
        break_frames.append((shift_frame(best['frame'], offset=break_frame_offset), best['peak'], best['total_turn']))
        break_indices.append(best['peak'])
        break_angles.append(df_player['angle_change_rate'].iloc[best['peak']])

    # if there is no break detected, check for a late window fallback 
    if enable_late_window_fallback and not break_frames:
        lookback = fallback_lookback if fallback_lookback is not None else window
        min_rise = fallback_min_rise if fallback_min_rise is not None else min_angle_change

        n = len(df_player)
        tail_n = min(lookback, n)

        if tail_n >= 3:
            raw_dir = df_player['dir'].values
            raw_diff = np.abs(np.diff(raw_dir, prepend=raw_dir[0]))
            raw_diff = np.where(raw_diff > 180, 360 - raw_diff, raw_diff)

            trailing_rate = pd.Series(raw_diff).rolling(lookback, min_periods=1, center=False).mean().values

            tail_start = n - tail_n
            tail_rates = trailing_rate[tail_start:]
            tail_x = np.arange(tail_n)

            slope = np.polyfit(tail_x, tail_rates, 1)[0]
            recent_rise = tail_rates[-1] - tail_rates[0]

            is_dramatically_rising = slope > 0 and recent_rise >= min_rise
            median_rate = np.median(df_player['angle_change_rate'])
            end_rate = df_player['angle_change_rate'].iloc[-1]
            print(end_rate, median_rate, is_dramatically_rising, df_player['displayName'].iloc[0], df_player['gsis_play_id'].iloc[0])

            if is_dramatically_rising:
                fallback_idx = max(0, n - 1 - 2)
                fallback_x = df_player['x'].iloc[fallback_idx]

                if _passes_los(fallback_x):
                    fallback_frame = df_player['frame_id'].iloc[fallback_idx]
                    start_idx = max(0, fallback_idx - 1)
                    end_idx = min(n - 1, fallback_idx + 1)
                    fallback_turn = float(np.sum(df_player['angle_change_rate'].iloc[start_idx:end_idx + 1]))

                    break_frames.append((shift_frame(fallback_frame, offset=break_frame_offset), fallback_idx, fallback_turn))
                    break_indices.append(fallback_idx)
                    break_angles.append(df_player['angle_change_rate'].iloc[fallback_idx])

            if not break_frames:
                print(f"No route break detected for player {df_player['displayName'].iloc[0]} in play {df_player['gsis_play_id'].iloc[0]}.")
                median_rate = np.nanmedian(df_player['angle_change_rate'])
                end_rate = df_player['angle_change_rate'].iloc[-1]
                if end_rate > 2 and median_rate > 2:
                    print(f"Player {df_player['displayName'].iloc[0]} in play {df_player['gsis_play_id'].iloc[0]} has end rate {end_rate} above median rate {median_rate}.")

    return df_player, peaks, break_frames, break_indices, break_angles

In [55]:
def plot_route_with_breaks(df_player, peaks, break_indices):
    fig, (ax_map, ax_rate) = plt.subplots(1, 2, figsize=(14, 6))

    los_x = df_player['x_ball_at_snap'].iloc[0]
    los_y = df_player['y_ball_at_snap'].iloc[0]
    play_direction = df_player['play_direction'].iloc[0]

    if pd.notna(los_x) and pd.notna(los_y) and pd.notna(play_direction):
        arrow_dx = 8 if str(play_direction).strip().lower() == 'right' else -8
        ax_map.annotate(
            '', xy=(los_x + arrow_dx, los_y), xytext=(los_x, los_y),
            arrowprops=dict(arrowstyle='-|>', color='darkorange', linewidth=2, mutation_scale=20),
            zorder=5  # bumped above the route line so it's never visually buried
        )
    else:
        arrow_dx = 0
        print(f"Skipping direction arrow for {df_player['displayName'].iloc[0]} — "
              f"los_x={los_x}, los_y={los_y}, play_direction={play_direction}")

    ax_map.axvline(los_x, color='gray', linewidth=1, linestyle='--', alpha=0.6, zorder=0, label='Line of scrimmage')

    ax_map.plot(df_player['x'], df_player['y'], color='steelblue', linewidth=1.5, zorder=1)
    ax_map.scatter(df_player['x'].iloc[0], df_player['y'].iloc[0],
                    color='green', marker='o', s=80, zorder=3, label='Start')
    ax_map.scatter(df_player['x'].iloc[-1], df_player['y'].iloc[-1],
                    color='black', marker='s', s=80, zorder=3, label='End')

    other_peaks = [p for p in peaks if p not in break_indices]
    if other_peaks:
        ax_map.scatter(df_player['x'].iloc[other_peaks], df_player['y'].iloc[other_peaks],
                        color='gray', marker='x', s=60, zorder=2, label='Candidate (below threshold)')

    if break_indices:
        ax_map.scatter(df_player['x'].iloc[break_indices], df_player['y'].iloc[break_indices],
                        color='red', marker='*', s=220, edgecolors='black',
                        linewidths=0.8, zorder=4, label='Route break')
        for idx in break_indices:
            x_pos = df_player['x'].iloc[idx]
            y_pos = df_player['y'].iloc[idx]
            frame_id = df_player['frame_id'].iloc[idx]
            ax_map.annotate(
                f'Frame {frame_id}', (x_pos, y_pos),
                textcoords="offset points", xytext=(0, 10), ha='center',
                fontsize=8, fontweight='bold', zorder=6,
                bbox=dict(boxstyle="round,pad=0.2", fc="white", ec="red", lw=0.8, alpha=0.8)
            )

    # explicit axis limits: cover the full route AND the arrow, with padding, so nothing gets squashed
    all_x = list(df_player['x']) + [los_x, los_x + arrow_dx]
    all_y = list(df_player['y']) + [los_y]
    pad = 3
    ax_map.set_xlim(min(all_x) - pad, max(all_x) + pad)
    ax_map.set_ylim(min(all_y) - pad, max(all_y) + pad)

    ax_map.set_title(f"Route Path — {df_player['displayName'].iloc[0]} — {df_player['route'].iloc[0]}")
    ax_map.set_aspect('equal')
    ax_map.legend(loc='best', fontsize=8)

    ax_rate.plot(df_player['frame_id'], df_player['angle_change_rate'],
                 color='steelblue', linewidth=1.2, zorder=1)
    if other_peaks:
        ax_rate.scatter(df_player['frame_id'].iloc[other_peaks],
                         df_player['angle_change_rate'].iloc[other_peaks],
                         color='gray', marker='x', s=60, zorder=2)
    if break_indices:
        ax_rate.scatter(df_player['frame_id'].iloc[break_indices],
                         df_player['angle_change_rate'].iloc[break_indices],
                         color='red', marker='*', s=220, edgecolors='black',
                         linewidths=0.8, zorder=3)

    ax_rate.set_xlim(df_player['frame_id'].min(), df_player['frame_id'].max())
    ax_rate.xaxis.set_major_locator(MultipleLocator(10))
    ax_rate.set_title("Angle Change Rate")
    ax_rate.set_xlabel("Frame ID")
    ax_rate.set_ylabel("Degrees / frame")

    plt.tight_layout()
    plt.show()

In [56]:
# Number of extra rows to include past the play's true submit boundary, so the
# centered rolling-average smoothing (window=5, center=True) has real future
# frames to average against near the end of the window instead of silently
# suppressing a real break that happens right at/after the end event.
BUFFER_FRAMES = 0

unique_player_plays = tracking_data[['game_id', 'gsis_play_id', 'nfl_id']].drop_duplicates()

break_frames_final = []

for _, row in unique_player_plays.iterrows():
    player_df = tracking_data[
        (tracking_data['game_id'] == row['game_id']) &
        (tracking_data['gsis_play_id'] == row['gsis_play_id']) &
        (tracking_data['nfl_id'] == row['nfl_id'])
    ].sort_values('frame_id').reset_index(drop=True)

    snap_frames = player_df.loc[player_df['event'] == 'ball_snap', 'time']
    end_events = ['pass_outcome_caught', 'pass_arrived', 'out_of_bounds', 'pass_outcome_incomplete',
                    'dropped_pass', 'pass_tipped', 'qb_spike']

    submit_frames = player_df.loc[player_df['event'].isin(end_events), 'time'].sort_values()

    if submit_frames.empty:
        submit_frames = player_df.loc[player_df['event'] == 'play_submit', 'time']

    # skip if this player/play doesn't have both events
    if snap_frames.empty or submit_frames.empty:
        continue

    snap_frame = snap_frames.iloc[0]
    submit_frame = submit_frames.iloc[0]

    # Find row positions for the snap and true submit boundary, then extend
    # the end by BUFFER_FRAMES extra rows (if available) so the rolling
    # smoothing has real context past the boundary. Extending by row count
    # rather than a time delta avoids assumptions about frame rate.
    in_range_idx = player_df.index[
        (player_df['time'] >= snap_frame) & (player_df['time'] <= submit_frame)
    ]

    if len(in_range_idx) == 0:
        continue

    snap_idx = in_range_idx.min()
    submit_idx = in_range_idx.max()
    buffered_end_idx = min(len(player_df) - 1, submit_idx + BUFFER_FRAMES)

    result_df = player_df.loc[snap_idx:buffered_end_idx].reset_index(drop=True)

    # Mark which rows fall within the TRUE (non-buffer) window — detect_route_break
    # uses this to restrict candidate peak search and the late-window fallback to
    # real play frames, while still letting the smoothing calc use the full
    # buffered range for better accuracy at the tail.
    result_df['in_true_window'] = result_df['time'] <= submit_frame

    df_player, peaks, break_frames, break_indices, break_angles = detect_route_break(result_df, route_offsets=ROUTE_BREAK_FRAME_OFFSETS)
    # print(row['nfl_id'], df_player[['x_ball_at_snap', 'y_ball_at_snap', 'play_direction']].iloc[0].to_dict())
    # plot_route_with_breaks(df_player, peaks, break_indices)

    if break_frames:
        # print(break_angles, 'break_angles', break_frames, 'break_frames')
        mask = (
            (tracking_data['game_id'] == row['game_id']) &
            (tracking_data['gsis_play_id'] == row['gsis_play_id']) &
            (tracking_data['nfl_id'] == row['nfl_id'])
        )
        tracking_data.loc[mask, 'route_break_frame'] = break_frames[0][0]

    # print(break_frames[0], 'asdfasdf')
    if len(break_frames) > 1: # if there are multiple break frames, take the highest peak one (the first is usually a false positive)
        final_break_frame = max(break_frames, key=lambda b: b[2])
    elif len(break_frames) == 1: # if there is only one break frame, take that one, convert from list
        final_break_frame = break_frames[0]
    else:
        final_break_frame = break_frames # else get the empty item

    break_frames_final.append((row['game_id'], row['gsis_play_id'], row['nfl_id'],
                               result_df['displayName'].iloc[0], final_break_frame, result_df['play_direction'].iloc[0]))
    # print(result_df['displayName'].iloc[0], break_frames)
    # print(len(break_frames))
    print((row['game_id'], row['gsis_play_id'], row['nfl_id'], result_df['displayName'].iloc[0], final_break_frame))

break_frames_final

(np.float64(2025090400.0), np.float64(1933.0), np.float64(52425.0), 'CeeDee Lamb', [])
(np.float64(2025090400.0), np.float64(1933.0), np.float64(53117.0), 'KaVontae Turpin', ('2025090400-1933-199', np.int64(24), np.float64(8.801361646728111)))
(np.float64(2025090400.0), np.float64(1933.0), np.float64(53464.0), 'Javonte Williams', ('2025090400-1933-202', np.int64(27), np.float64(20.36060313608209)))
(np.float64(2025090400.0), np.float64(1933.0), np.float64(54517.0), 'George Pickens', ('2025090400-1933-201', np.int64(28), np.float64(11.380861782490257)))
(np.float64(2025090400.0), np.float64(1933.0), np.float64(54594.0), 'Jake Ferguson', ('2025090400-1933-197', np.int64(22), np.float64(15.177953075688265)))
(np.float64(2025090400.0), np.float64(2164.0), np.float64(46071.0), 'Saquon Barkley', ('2025090400-2164-150', np.int64(11), np.float64(9.27975077199102)))
(np.float64(2025090400.0), np.float64(2164.0), np.float64(46118.0), 'Dallas Goedert', ('2025090400-2164-163', np.int64(24), np.float64(17.752010358191257)))
(np.float64(2025090400.0), np.float64(2164.0), np.float64(47834.0), 'A.J. Brown', ('2025090400-2164-155', np.int64(16), np.float64(8.993104212046191)))
(np.float64(2025090400.0), np.float64(2164.0), np.float64(53439.0), 'DeVonta Smith', ('2025090400-2164-158', np.int64(19), np.float64(17.273912306212736)))
(np.float64(2025090400.0), np.float64(2164.0), np.float64(54663.0), 'Grant Calcaterra', ('2025090400-2164-170', np.int64(31), np.float64(11.614337464869493)))
(np.float64(2025090400.0), np.float64(3451.0), np.float64(52425.0), 'CeeDee Lamb', ('2025090400-3451-235', np.int64(38), np.float64(13.268632497348534)))
(np.float64(2025090400.0), np.float64(3451.0), np.float64(53117.0), 'KaVontae Turpin', ('2025090400-3451-236', np.int64(38), np.float64(11.45302233434218)))
(np.float64(2025090400.0), np.float64(3451.0), np.float64(53464.0), 'Javonte Williams', ('2025090400-3451-209', np.int64(11), np.float64(20.699575441183356)))
(np.float64(2025090400.0), np.float64(3451.0), np.float64(54517.0), 'George Pickens', ('2025090400-3451-233', np.int64(36), np.float64(17.24233330194135)))
(np.float64(2025090400.0), np.float64(3451.0), np.float64(54594.0), 'Jake Ferguson', ('2025090400-3451-245', np.int64(47), np.float64(14.057542934256219)))
(np.float64(2025090400.0), np.float64(3643.0), np.float64(52425.0), 'CeeDee Lamb', ('2025090400-3643-074', np.int64(37), np.float64(35.81551440783238)))
(np.float64(2025090400.0), np.float64(3643.0), np.float64(53464.0), 'Javonte Williams', ('2025090400-3643-072', np.int64(34), np.float64(23.32152214294223)))
(np.float64(2025090400.0), np.float64(3643.0), np.float64(54517.0), 'George Pickens', ('2025090400-3643-070', np.int64(31), np.float64(27.862375636210242)))
(np.float64(2025090400.0), np.float64(3643.0), np.float64(54553.0), 'Jalen Tolbert', ('2025090400-3643-066', np.int64(29), np.float64(56.02568672340925)))
(np.float64(2025090400.0), np.float64(3643.0), np.float64(54594.0), 'Jake Ferguson', ('2025090400-3643-067', np.int64(28), np.float64(28.242884684858183)))
(np.float64(2025090400.0), np.float64(3724.0), np.float64(53117.0), 'KaVontae Turpin', ('2025090400-3724-134', np.int64(32), np.float64(34.01428271863833)))
0.0 0.0 False Javonte Williams 3724
No route break detected for player Javonte Williams in play 3724.
(np.float64(2025090400.0), np.float64(3724.0), np.float64(53464.0), 'Javonte Williams', [])
(np.float64(2025090400.0), np.float64(3724.0), np.float64(54517.0), 'George Pickens', ('2025090400-3724-134', np.int64(31), np.float64(18.144556460528605)))
(np.float64(2025090400.0), np.float64(3724.0), np.float64(54553.0), 'Jalen Tolbert', ('2025090400-3724-135', np.int64(34), np.float64(7.800180000543378)))
(np.float64(2025090400.0), np.float64(3724.0), np.float64(55923.0), 'Luke Schoonmaker', ('2025090400-3724-137', np.int64(34), np.float64(10.090435480386844)))
(np.float64(2025090400.0), np.float64(3671.0), np.float64(52425.0), 'CeeDee Lamb', ('2025090400-3671-176', np.int64(29), np.float64(17.828518222781717)))
0.27833143614580536 0.8071306412439014 False Javonte Williams 3671
No route break detected for player Javonte Williams in play 3671.
(np.float64(2025090400.0), np.float64(3671.0), np.float64(53464.0), 'Javonte Williams', [])
(np.float64(2025090400.0), np.float64(3671.0), np.float64(54517.0), 'George Pickens', ('2025090400-3671-180', np.int64(32), np.float64(20.201747257330197)))
(np.float64(2025090400.0), np.float64(3671.0), np.float64(54553.0), 'Jalen Tolbert', ('2025090400-3671-166', np.int64(18), np.float64(14.925506879102528)))
(np.float64(2025090400.0), np.float64(3671.0), np.float64(54594.0), 'Jake Ferguson', ('2025090400-3671-178', np.int64(32), np.float64(22.9164234772853)))
(np.float64(2025090400.0), np.float64(3701.0), np.float64(52425.0), 'CeeDee Lamb', [])
(np.float64(2025090400.0), np.float64(3701.0), np.float64(53464.0), 'Javonte Williams', ('2025090400-3701-080', np.int64(53), np.float64(9.475649037649632)))
(np.float64(2025090400.0), np.float64(3701.0), np.float64(54517.0), 'George Pickens', ('2025090400-3701-052', np.int64(27), np.float64(12.205456354133204)))
(np.float64(2025090400.0), np.float64(3701.0), np.float64(54553.0), 'Jalen Tolbert', [])
(np.float64(2025090400.0), np.float64(3701.0), np.float64(54594.0), 'Jake Ferguson', [])
(np.float64(2025090400.0), np.float64(1958.0), np.float64(52425.0), 'CeeDee Lamb', [])
(np.float64(2025090400.0), np.float64(1958.0), np.float64(53464.0), 'Javonte Williams', ('2025090400-1958-087', np.int64(42), np.float64(8.1514110199671)))
(np.float64(2025090400.0), np.float64(1958.0), np.float64(54517.0), 'George Pickens', ('2025090400-1958-084', np.int64(38), np.float64(24.994681762931947)))
(np.float64(2025090400.0), np.float64(1958.0), np.float64(54553.0), 'Jalen Tolbert', ('2025090400-1958-072', np.int64(26), np.float64(9.398488458214729)))
(np.float64(2025090400.0), np.float64(1958.0), np.float64(54594.0), 'Jake Ferguson', ('2025090400-1958-062', np.int64(16), np.float64(35.874773785355615)))
0.8748461105143406 1.6010328601221175 False Saquon Barkley 1695
No route break detected for player Saquon Barkley in play 1695.
(np.float64(2025090400.0), np.float64(1695.0), np.float64(46071.0), 'Saquon Barkley', [])
(np.float64(2025090400.0), np.float64(1695.0), np.float64(46118.0), 'Dallas Goedert', ('2025090400-1695-194', np.int64(30), np.float64(13.521535334392986)))
(np.float64(2025090400.0), np.float64(1695.0), np.float64(47834.0), 'A.J. Brown', ('2025090400-1695-185', np.int64(21), np.float64(32.738491830304355)))
(np.float64(2025090400.0), np.float64(1695.0), np.float64(53439.0), 'DeVonta Smith', [])
(np.float64(2025090400.0), np.float64(1695.0), np.float64(54481.0), 'Jahan Dotson', ('2025090400-1695-193', np.int64(30), np.float64(38.44046548681396)))
0.8749730785525571 0.39398516352390267 True Saquon Barkley 330
No route break detected for player Saquon Barkley in play 330.
(np.float64(2025090400.0), np.float64(330.0), np.float64(46071.0), 'Saquon Barkley', [])
(np.float64(2025090400.0), np.float64(330.0), np.float64(46118.0), 'Dallas Goedert', ('2025090400-330-218', np.int64(15), np.float64(6.372124028130969)))
(np.float64(2025090400.0), np.float64(330.0), np.float64(47834.0), 'A.J. Brown', ('2025090400-330-230', np.int64(30), np.float64(6.344268774492491)))
(np.float64(2025090400.0), np.float64(330.0), np.float64(53439.0), 'DeVonta Smith', ('2025090400-330-228', np.int64(26), np.float64(22.62659668826157)))
1.8907362577031108 0.7800274177373581 True Jahan Dotson 330
No route break detected for player Jahan Dotson in play 330.
(np.float64(2025090400.0), np.float64(330.0), np.float64(54481.0), 'Jahan Dotson', [])
(np.float64(2025090400.0), np.float64(1995.0), np.float64(52425.0), 'CeeDee Lamb', ('2025090400-1995-173', np.int64(14), np.float64(23.672079135240267)))
0.1141676101253779 0.2659990835973076 False Javonte Williams 1995
No route break detected for player Javonte Williams in play 1995.
(np.float64(2025090400.0), np.float64(1995.0), np.float64(53464.0), 'Javonte Williams', [])
(np.float64(2025090400.0), np.float64(1995.0), np.float64(54517.0), 'George Pickens', ('2025090400-1995-179', np.int64(17), np.float64(16.278493793426406)))
(np.float64(2025090400.0), np.float64(1995.0), np.float64(54553.0), 'Jalen Tolbert', ('2025090400-1995-174', np.int64(13), np.float64(12.283894943777938)))
(np.float64(2025090400.0), np.float64(1995.0), np.float64(54594.0), 'Jake Ferguson', [])
(np.float64(2025090400.0), np.float64(717.0), np.float64(52425.0), 'CeeDee Lamb', ('2025090400-717-186', np.int64(25), np.float64(12.836558322613897)))
(np.float64(2025090400.0), np.float64(717.0), np.float64(53464.0), 'Javonte Williams', ('2025090400-717-200', np.int64(40), np.float64(9.135444951151158)))
(np.float64(2025090400.0), np.float64(717.0), np.float64(54517.0), 'George Pickens', [])
(np.float64(2025090400.0), np.float64(717.0), np.float64(54553.0), 'Jalen Tolbert', ('2025090400-717-198', np.int64(40), np.float64(15.25245945543083)))
(np.float64(2025090400.0), np.float64(717.0), np.float64(54594.0), 'Jake Ferguson', ('2025090400-717-179', np.int64(18), np.float64(23.21025581474745)))
(np.float64(2025090400.0), np.float64(2984.0), np.float64(52425.0), 'CeeDee Lamb', ('2025090400-2984-123', np.int64(28), np.float64(17.541157630049035)))
(np.float64(2025090400.0), np.float64(2984.0), np.float64(53117.0), 'KaVontae Turpin', [])
2.297401201291649 1.5379583196029216 True Javonte Williams 2984
No route break detected for player Javonte Williams in play 2984.
(np.float64(2025090400.0), np.float64(2984.0), np.float64(53464.0), 'Javonte Williams', [])
(np.float64(2025090400.0), np.float64(2984.0), np.float64(54517.0), 'George Pickens', [])
1.5173587042675365 0.08999962111514037 True Jake Ferguson 2984
No route break detected for player Jake Ferguson in play 2984.
(np.float64(2025090400.0), np.float64(2984.0), np.float64(54594.0), 'Jake Ferguson', [])
(np.float64(2025090400.0), np.float64(3606.0), np.float64(52425.0), 'CeeDee Lamb', [])
1.078612098427019 1.3769025513062445 True Javonte Williams 3606
No route break detected for player Javonte Williams in play 3606.
(np.float64(2025090400.0), np.float64(3606.0), np.float64(53464.0), 'Javonte Williams', [])
(np.float64(2025090400.0), np.float64(3606.0), np.float64(54517.0), 'George Pickens', ('2025090400-3606-099', np.int64(28), np.float64(17.732986708220736)))
(np.float64(2025090400.0), np.float64(3606.0), np.float64(54553.0), 'Jalen Tolbert', ('2025090400-3606-092', np.int64(22), np.float64(10.168604603702207)))
(np.float64(2025090400.0), np.float64(3606.0), np.float64(54594.0), 'Jake Ferguson', ('2025090400-3606-096', np.int64(24), np.float64(14.38533328081175)))
(np.float64(2025090400.0), np.float64(3266.0), np.float64(46118.0), 'Dallas Goedert', ('2025090400-3266-130', np.int64(27), np.float64(39.23544180620854)))
(np.float64(2025090400.0), np.float64(3266.0), np.float64(47834.0), 'A.J. Brown', ('2025090400-3266-127', np.int64(25), np.float64(19.09374941108092)))
(np.float64(2025090400.0), np.float64(3266.0), np.float64(52470.0), 'AJ Dillon', ('2025090400-3266-170', np.int64(65), np.float64(16.944206758689973)))
(np.float64(2025090400.0), np.float64(3266.0), np.float64(53439.0), 'DeVonta Smith', ('2025090400-3266-150', np.int64(47), np.float64(35.556415457467466)))
(np.float64(2025090400.0), np.float64(3266.0), np.float64(54481.0), 'Jahan Dotson', ('2025090400-3266-137', np.int64(32), np.float64(15.981754553011285)))
(np.float64(2025090400.0), np.float64(2609.0), np.float64(52425.0), 'CeeDee Lamb', ('2025090400-2609-172', np.int64(21), np.float64(19.098464434776588)))
0.7776182977188455 0.7217756033202534 False Javonte Williams 2609
No route break detected for player Javonte Williams in play 2609.
(np.float64(2025090400.0), np.float64(2609.0), np.float64(53464.0), 'Javonte Williams', [])
(np.float64(2025090400.0), np.float64(2609.0), np.float64(54517.0), 'George Pickens', ('2025090400-2609-170', np.int64(19), np.float64(16.967995713319624)))
(np.float64(2025090400.0), np.float64(2609.0), np.float64(54553.0), 'Jalen Tolbert', ('2025090400-2609-169', np.int64(15), np.float64(8.910541294977804)))
(np.float64(2025090400.0), np.float64(2609.0), np.float64(54594.0), 'Jake Ferguson', ('2025090400-2609-172', np.int64(22), np.float64(8.100014211085522)))
(np.float64(2025090400.0), np.float64(2498.0), np.float64(52425.0), 'CeeDee Lamb', ('2025090400-2498-159', np.int64(21), np.float64(20.987780348202023)))
0.4999829516870591 1.806071559801718 False Javonte Williams 2498
No route break detected for player Javonte Williams in play 2498.
(np.float64(2025090400.0), np.float64(2498.0), np.float64(53464.0), 'Javonte Williams', [])
(np.float64(2025090400.0), np.float64(2498.0), np.float64(54517.0), 'George Pickens', [])
(np.float64(2025090400.0), np.float64(2498.0), np.float64(55923.0), 'Luke Schoonmaker', ('2025090400-2498-150', np.int64(11), np.float64(14.976338231828493)))
(np.float64(2025090400.0), np.float64(2498.0), np.float64(57649.0), 'Brevyn Spann-Ford', [])
(np.float64(2025090400.0), np.float64(2867.0), np.float64(52425.0), 'CeeDee Lamb', ('2025090400-2867-207', np.int64(27), np.float64(18.9525715071766)))
(np.float64(2025090400.0), np.float64(2867.0), np.float64(53117.0), 'KaVontae Turpin', [])
(np.float64(2025090400.0), np.float64(2867.0), np.float64(54517.0), 'George Pickens', [])
(np.float64(2025090400.0), np.float64(2867.0), np.float64(54594.0), 'Jake Ferguson', ('2025090400-2867-198', np.int64(17), np.float64(17.585233387459937)))
(np.float64(2025090400.0), np.float64(1647.0), np.float64(46071.0), 'Saquon Barkley', ('2025090400-1647-242', np.int64(47), np.float64(12.953484988276223)))
(np.float64(2025090400.0), np.float64(1647.0), np.float64(46118.0), 'Dallas Goedert', ('2025090400-1647-223', np.int64(29), np.float64(15.369537005263311)))
(np.float64(2025090400.0), np.float64(1647.0), np.float64(47834.0), 'A.J. Brown', ('2025090400-1647-228', np.int64(35), np.float64(18.911717675831483)))
(np.float64(2025090400.0), np.float64(1647.0), np.float64(53439.0), 'DeVonta Smith', ('2025090400-1647-238', np.int64(46), np.float64(11.858228751147202)))
0.17833232198917415 0.613984080684574 False Jahan Dotson 1647
No route break detected for player Jahan Dotson in play 1647.
(np.float64(2025090400.0), np.float64(1647.0), np.float64(54481.0), 'Jahan Dotson', [])
2.34825927921219 2.364879847185373 False Saquon Barkley 1043
No route break detected for player Saquon Barkley in play 1043.
Player Saquon Barkley in play 1043 has end rate 2.34825927921219 above median rate 2.364879847185373.
(np.float64(2025090400.0), np.float64(1043.0), np.float64(46071.0), 'Saquon Barkley', [])
(np.float64(2025090400.0), np.float64(1043.0), np.float64(46118.0), 'Dallas Goedert', ('2025090400-1043-223', np.int64(26), np.float64(40.797087014412554)))
(np.float64(2025090400.0), np.float64(1043.0), np.float64(47834.0), 'A.J. Brown', [])
(np.float64(2025090400.0), np.float64(1043.0), np.float64(53439.0), 'DeVonta Smith', ('2025090400-1043-227', np.int64(28), np.float64(11.416344737177468)))
(np.float64(2025090400.0), np.float64(1043.0), np.float64(54481.0), 'Jahan Dotson', ('2025090400-1043-233', np.int64(35), np.float64(20.102278299793454)))
(np.float64(2025090400.0), np.float64(1725.0), np.float64(46071.0), 'Saquon Barkley', ('2025090400-1725-235', np.int64(26), np.float64(23.741615076045527)))
(np.float64(2025090400.0), np.float64(1725.0), np.float64(46118.0), 'Dallas Goedert', ('2025090400-1725-232', np.int64(23), np.float64(15.155449806515435)))
(np.float64(2025090400.0), np.float64(1725.0), np.float64(47834.0), 'A.J. Brown', ('2025090400-1725-226', np.int64(14), np.float64(11.794243454509214)))
(np.float64(2025090400.0), np.float64(1725.0), np.float64(53439.0), 'DeVonta Smith', ('2025090400-1725-236', np.int64(27), np.float64(13.588705814880797)))
(np.float64(2025090400.0), np.float64(1725.0), np.float64(54481.0), 'Jahan Dotson', ('2025090400-1725-224', np.int64(12), np.float64(24.85975588267349)))
3.4129225408829313 2.960181093560891 True Saquon Barkley 3219
No route break detected for player Saquon Barkley in play 3219.
Player Saquon Barkley in play 3219 has end rate 3.4129225408829313 above median rate 2.960181093560891.
(np.float64(2025090400.0), np.float64(3219.0), np.float64(46071.0), 'Saquon Barkley', [])
(np.float64(2025090400.0), np.float64(3219.0), np.float64(47834.0), 'A.J. Brown', [])
(np.float64(2025090400.0), np.float64(3219.0), np.float64(53439.0), 'DeVonta Smith', [])
(np.float64(2025090400.0), np.float64(3219.0), np.float64(53556.0), 'Kylen Granson', ('2025090400-3219-115', np.int64(28), np.float64(13.474264383498564)))
(np.float64(2025090400.0), np.float64(3219.0), np.float64(54663.0), 'Grant Calcaterra', ('2025090400-3219-112', np.int64(25), np.float64(10.925048961152243)))
(np.float64(2025090400.0), np.float64(3027.0), np.float64(46071.0), 'Saquon Barkley', ('2025090400-3027-236', np.int64(41), np.float64(9.564811712092904)))
(np.float64(2025090400.0), np.float64(3027.0), np.float64(46118.0), 'Dallas Goedert', ('2025090400-3027-215', np.int64(20), np.float64(11.035458963679048)))
(np.float64(2025090400.0), np.float64(3027.0), np.float64(47834.0), 'A.J. Brown', ('2025090400-3027-211', np.int64(13), np.float64(19.143571176761043)))
(np.float64(2025090400.0), np.float64(3027.0), np.float64(53439.0), 'DeVonta Smith', ('2025090400-3027-218', np.int64(23), np.float64(8.101908711070053)))
(np.float64(2025090400.0), np.float64(3027.0), np.float64(54663.0), 'Grant Calcaterra', ('2025090400-3027-214', np.int64(18), np.float64(12.93007048827215)))
(np.float64(2025090400.0), np.float64(1326.0), np.float64(52425.0), 'CeeDee Lamb', ('2025090400-1326-165', np.int64(28), np.float64(10.611578821146935)))
(np.float64(2025090400.0), np.float64(1326.0), np.float64(53117.0), 'KaVontae Turpin', [])
(np.float64(2025090400.0), np.float64(1326.0), np.float64(54517.0), 'George Pickens', ('2025090400-1326-165', np.int64(27), np.float64(18.988716214494445)))
(np.float64(2025090400.0), np.float64(1326.0), np.float64(54594.0), 'Jake Ferguson', [])
(np.float64(2025090400.0), np.float64(1093.0), np.float64(46071.0), 'Saquon Barkley', ('2025090400-1093-215', np.int64(7), np.float64(5.253247537442881)))
(np.float64(2025090400.0), np.float64(1093.0), np.float64(46118.0), 'Dallas Goedert', ('2025090400-1093-245', np.int64(40), np.float64(14.902024851432078)))
(np.float64(2025090400.0), np.float64(1093.0), np.float64(53439.0), 'DeVonta Smith', ('2025090400-1093-233', np.int64(26), np.float64(15.320858525741258)))
(np.float64(2025090400.0), np.float64(1093.0), np.float64(53556.0), 'Kylen Granson', ('2025090400-1093-220', np.int64(12), np.float64(28.75700357629681)))
0.03333393864534173 0.5077989338745823 False CeeDee Lamb 141
No route break detected for player CeeDee Lamb in play 141.
(np.float64(2025090400.0), np.float64(141.0), np.float64(52425.0), 'CeeDee Lamb', [])
0.9174975444234992 3.2882597836754144 False KaVontae Turpin 141
No route break detected for player KaVontae Turpin in play 141.
(np.float64(2025090400.0), np.float64(141.0), np.float64(53117.0), 'KaVontae Turpin', [])
(np.float64(2025090400.0), np.float64(141.0), np.float64(54517.0), 'George Pickens', ('2025090400-141-176', np.int64(21), np.float64(10.72388652736187)))
(np.float64(2025090400.0), np.float64(141.0), np.float64(55923.0), 'Luke Schoonmaker', [])
0.4317106406665516 1.3120006796537211 False Miles Sanders 778
No route break detected for player Miles Sanders in play 778.
(np.float64(2025090400.0), np.float64(778.0), np.float64(47836.0), 'Miles Sanders', [])
(np.float64(2025090400.0), np.float64(778.0), np.float64(53117.0), 'KaVontae Turpin', ('2025090400-778-197', np.int64(18), np.float64(12.94706014274545)))
(np.float64(2025090400.0), np.float64(778.0), np.float64(54517.0), 'George Pickens', ('2025090400-778-207', np.int64(29), np.float64(20.582462932601658)))

[(np.float64(2025090400.0),
  np.float64(1933.0),
  np.float64(52425.0),
  'CeeDee Lamb',
  [],
  'left'),
 (np.float64(2025090400.0),
  np.float64(1933.0),
  np.float64(53117.0),
  'KaVontae Turpin',
  ('2025090400-1933-199', np.int64(24), np.float64(8.801361646728111)),
  'left'),
 (np.float64(2025090400.0),
  np.float64(1933.0),
  np.float64(53464.0),
  'Javonte Williams',
  ('2025090400-1933-202', np.int64(27), np.float64(20.36060313608209)),
  'left'),
 (np.float64(2025090400.0),
  np.float64(1933.0),
  np.float64(54517.0),
  'George Pickens',
  ('2025090400-1933-201', np.int64(28), np.float64(11.380861782490257)),
  'left'),
 (np.float64(2025090400.0),
  np.float64(1933.0),
  np.float64(54594.0),
  'Jake Ferguson',
  ('2025090400-1933-197', np.int64(22), np.float64(15.177953075688265)),
  'left'),
 (np.float64(2025090400.0),
  np.float64(2164.0),
  np.float64(46071.0),
  'Saquon Barkley',
  ('2025090400-2164-150', np.int64(11), np.float64(9.27975077199102)),
  'right'),
 (np.float64(2025090400.0),
  np.float64(2164.0),
  np.float64(46118.0),
  'Dallas Goedert',
  ('2025090400-2164-163', np.int64(24), np.float64(17.752010358191257)),
  'right'),
 (np.float64(2025090400.0),
  np.float64(2164.0),
  np.float64(47834.0),
  'A.J. Brown',
  ('2025090400-2164-155', np.int64(16), np.float64(8.993104212046191)),
  'right'),
 (np.float64(2025090400.0),
  np.float64(2164.0),
  np.float64(53439.0),
  'DeVonta Smith',
  ('2025090400-2164-158', np.int64(19), np.float64(17.273912306212736)),
  'right'),
 (np.float64(2025090400.0),
  np.float64(2164.0),
  np.float64(54663.0),
  'Grant Calcaterra',
  ('2025090400-2164-170', np.int64(31), np.float64(11.614337464869493)),
  'right'),
 (np.float64(2025090400.0),
  np.float64(3451.0),
  np.float64(52425.0),
  'CeeDee Lamb',
  ('2025090400-3451-235', np.int64(38), np.float64(13.268632497348534)),
  'right'),
 (np.float64(2025090400.0),
  np.float64(3451.0),
  np.float64(53117.0),
  'KaVontae Turpin',
  ('2025090400-3451-236', np.int64(38), np.float64(11.45302233434218)),
  'right'),
 (np.float64(2025090400.0),
  np.float64(3451.0),
  np.float64(53464.0),
  'Javonte Williams',
  ('2025090400-3451-209', np.int64(11), np.float64(20.699575441183356)),
  'right'),
 (np.float64(2025090400.0),
  np.float64(3451.0),
  np.float64(54517.0),
  'George Pickens',
  ('2025090400-3451-233', np.int64(36), np.float64(17.24233330194135)),
  'right'),
 (np.float64(2025090400.0),
  np.float64(3451.0),
  np.float64(54594.0),
  'Jake Ferguson',
  ('2025090400-3451-245', np.int64(47), np.float64(14.057542934256219)),
  'right'),
 (np.float64(2025090400.0),
  np.float64(3643.0),
  np.float64(52425.0),
  'CeeDee Lamb',
  ('2025090400-3643-074', np.int64(37), np.float64(35.81551440783238)),
  'right'),
 (np.float64(2025090400.0),
  np.float64(3643.0),
  np.float64(53464.0),
  'Javonte Williams',
  ('2025090400-3643-072', np.int64(34), np.float64(23.32152214294223)),
  'right'),
 (np.float64(2025090400.0),
  np.float64(3643.0),
  np.float64(54517.0),
  'George Pickens',
  ('2025090400-3643-070', np.int64(31), np.float64(27.862375636210242)),
  'right'),
 (np.float64(2025090400.0),
  np.float64(3643.0),
  np.float64(54553.0),
  'Jalen Tolbert',
  ('2025090400-3643-066', np.int64(29), np.float64(56.02568672340925)),
  'right'),
 (np.float64(2025090400.0),
  np.float64(3643.0),
  np.float64(54594.0),
  'Jake Ferguson',
  ('2025090400-3643-067', np.int64(28), np.float64(28.242884684858183)),
  'right'),
 (np.float64(2025090400.0),
  np.float64(3724.0),
  np.float64(53117.0),
  'KaVontae Turpin',
  ('2025090400-3724-134', np.int64(32), np.float64(34.01428271863833)),
  'right'),
 (np.float64(2025090400.0),
  np.float64(3724.0),
  np.float64(53464.0),
  'Javonte Williams',
  [],
  'right'),
 (np.float64(2025090400.0),
  np.float64(3724.0),
  np.float64(54517.0),
  'George Pickens',
  ('2025090400-3724-134', np.int64(31), np.float64(18.144556460528605)),
  'right'),
 (np.float64(2025090400.0),
  np.float64(3724.0),
  np.float64(54553.0),
  'Jalen Tolbert',
  ('2025090400-3724-135', np.int64(34), np.float64(7.800180000543378)),
  'right'),
 (np.float64(2025090400.0),
  np.float64(3724.0),
  np.float64(55923.0),
  'Luke Schoonmaker',
  ('2025090400-3724-137', np.int64(34), np.float64(10.090435480386844)),
  'right'),
 (np.float64(2025090400.0),
  np.float64(3671.0),
  np.float64(52425.0),
  'CeeDee Lamb',
  ('2025090400-3671-176', np.int64(29), np.float64(17.828518222781717)),
  'right'),
 (np.float64(2025090400.0),
  np.float64(3671.0),
  np.float64(53464.0),
  'Javonte Williams',
  [],
  'right'),
 (np.float64(2025090400.0),
  np.float64(3671.0),
  np.float64(54517.0),
  'George Pickens',
  ('2025090400-3671-180', np.int64(32), np.float64(20.201747257330197)),
  'right'),
 (np.float64(2025090400.0),
  np.float64(3671.0),
  np.float64(54553.0),
  'Jalen Tolbert',
  ('2025090400-3671-166', np.int64(18), np.float64(14.925506879102528)),
  'right'),
 (np.float64(2025090400.0),
  np.float64(3671.0),
  np.float64(54594.0),
  'Jake Ferguson',
  ('2025090400-3671-178', np.int64(32), np.float64(22.9164234772853)),
  'right'),
 (np.float64(2025090400.0),
  np.float64(3701.0),
  np.float64(52425.0),
  'CeeDee Lamb',
  [],
  'right'),
 (np.float64(2025090400.0),
  np.float64(3701.0),
  np.float64(53464.0),
  'Javonte Williams',
  ('2025090400-3701-080', np.int64(53), np.float64(9.475649037649632)),
  'right'),
 (np.float64(2025090400.0),
  np.float64(3701.0),
  np.float64(54517.0),
  'George Pickens',
  ('2025090400-3701-052', np.int64(27), np.float64(12.205456354133204)),
  'right'),
 (np.float64(2025090400.0),
  np.float64(3701.0),
  np.float64(54553.0),
  'Jalen Tolbert',
  [],
  'right'),
 (np.float64(2025090400.0),
  np.float64(3701.0),
  np.float64(54594.0),
  'Jake Ferguson',
  [],
  'right'),
 (np.float64(2025090400.0),
  np.float64(1958.0),
  np.float64(52425.0),
  'CeeDee Lamb',
  [],
  'left'),
 (np.float64(2025090400.0),
  np.float64(1958.0),
  np.float64(53464.0),
  'Javonte Williams',
  ('2025090400-1958-087', np.int64(42), np.float64(8.1514110199671)),
  'left'),
 (np.float64(2025090400.0),
  np.float64(1958.0),
  np.float64(54517.0),
  'George Pickens',
  ('2025090400-1958-084', np.int64(38), np.float64(24.994681762931947)),
  'left'),
 (np.float64(2025090400.0),
  np.float64(1958.0),
  np.float64(54553.0),
  'Jalen Tolbert',
  ('2025090400-1958-072', np.int64(26), np.float64(9.398488458214729)),
  'left'),
 (np.float64(2025090400.0),
  np.float64(1958.0),
  np.float64(54594.0),
  'Jake Ferguson',
  ('2025090400-1958-062', np.int64(16), np.float64(35.874773785355615)),
  'left'),
 (np.float64(2025090400.0),
  np.float64(1695.0),
  np.float64(46071.0),
  'Saquon Barkley',
  [],
  'right'),
 (np.float64(2025090400.0),
  np.float64(1695.0),
  np.float64(46118.0),
  'Dallas Goedert',
  ('2025090400-1695-194', np.int64(30), np.float64(13.521535334392986)),
  'right'),
 (np.float64(2025090400.0),
  np.float64(1695.0),
  np.float64(47834.0),
  'A.J. Brown',
  ('2025090400-1695-185', np.int64(21), np.float64(32.738491830304355)),
  'right'),
 (np.float64(2025090400.0),
  np.float64(1695.0),
  np.float64(53439.0),
  'DeVonta Smith',
  [],
  'right'),
 (np.float64(2025090400.0),
  np.float64(1695.0),
  np.float64(54481.0),
  'Jahan Dotson',
  ('2025090400-1695-193', np.int64(30), np.float64(38.44046548681396)),
  'right'),
 (np.float64(2025090400.0),
  np.float64(330.0),
  np.float64(46071.0),
  'Saquon Barkley',
  [],
  'left'),
 (np.float64(2025090400.0),
  np.float64(330.0),
  np.float64(46118.0),
  'Dallas Goedert',
  ('2025090400-330-218', np.int64(15), np.float64(6.372124028130969)),
  'left'),
 (np.float64(2025090400.0),
  np.float64(330.0),
  np.float64(47834.0),
  'A.J. Brown',
  ('2025090400-330-230', np.int64(30), np.float64(6.344268774492491)),
  'left'),
 (np.float64(2025090400.0),
  np.float64(330.0),
  np.float64(53439.0),
  'DeVonta Smith',
  ('2025090400-330-228', np.int64(26), np.float64(22.62659668826157)),
  'left'),
 (np.float64(2025090400.0),
  np.float64(330.0),
  np.float64(54481.0),
  'Jahan Dotson',
  [],
  'left'),
 (np.float64(2025090400.0),
  np.float64(1995.0),
  np.float64(52425.0),
  'CeeDee Lamb',
  ('2025090400-1995-173', np.int64(14), np.float64(23.672079135240267)),
  'left'),
 (np.float64(2025090400.0),
  np.float64(1995.0),
  np.float64(53464.0),
  'Javonte Williams',
  [],
  'left'),
 (np.float64(2025090400.0),
  np.float64(1995.0),
  np.float64(54517.0),
  'George Pickens',
  ('2025090400-1995-179', np.int64(17), np.float64(16.278493793426406)),
  'left'),
 (np.float64(2025090400.0),
  np.float64(1995.0),
  np.float64(54553.0),
  'Jalen Tolbert',
  ('2025090400-1995-174', np.int64(13), np.float64(12.283894943777938)),
  'left'),
 (np.float64(2025090400.0),
  np.float64(1995.0),
  np.float64(54594.0),
  'Jake Ferguson',
  [],
  'left'),
 (np.float64(2025090400.0),
  np.float64(717.0),
  np.float64(52425.0),
  'CeeDee Lamb',
  ('2025090400-717-186', np.int64(25), np.float64(12.836558322613897)),
  'right'),
 (np.float64(2025090400.0),
  np.float64(717.0),
  np.float64(53464.0),
  'Javonte Williams',
  ('2025090400-717-200', np.int64(40), np.float64(9.135444951151158)),
  'right'),
 (np.float64(2025090400.0),
  np.float64(717.0),
  np.float64(54517.0),
  'George Pickens',
  [],
  'right'),
 (np.float64(2025090400.0),
  np.float64(717.0),
  np.float64(54553.0),
  'Jalen Tolbert',
  ('2025090400-717-198', np.int64(40), np.float64(15.25245945543083)),
  'right'),
 (np.float64(2025090400.0),
  np.float64(717.0),
  np.float64(54594.0),
  'Jake Ferguson',
  ('2025090400-717-179', np.int64(18), np.float64(23.21025581474745)),
  'right'),
 (np.float64(2025090400.0),
  np.float64(2984.0),
  np.float64(52425.0),
  'CeeDee Lamb',
  ('2025090400-2984-123', np.int64(28), np.float64(17.541157630049035)),
  'right'),
 (np.float64(2025090400.0),
  np.float64(2984.0),
  np.float64(53117.0),
  'KaVontae Turpin',
  [],
  'right'),
 (np.float64(2025090400.0),
  np.float64(2984.0),
  np.float64(53464.0),
  'Javonte Williams',
  [],
  'right'),
 (np.float64(2025090400.0),
  np.float64(2984.0),
  np.float64(54517.0),
  'George Pickens',
  [],
  'right'),
 (np.float64(2025090400.0),
  np.float64(2984.0),
  np.float64(54594.0),
  'Jake Ferguson',
  [],
  'right'),
 (np.float64(2025090400.0),
  np.float64(3606.0),
  np.float64(52425.0),
  'CeeDee Lamb',
  [],
  'right'),
 (np.float64(2025090400.0),
  np.float64(3606.0),
  np.float64(53464.0),
  'Javonte Williams',
  [],
  'right'),
 (np.float64(2025090400.0),
  np.float64(3606.0),
  np.float64(54517.0),
  'George Pickens',
  ('2025090400-3606-099', np.int64(28), np.float64(17.732986708220736)),
  'right'),
 (np.float64(2025090400.0),
  np.float64(3606.0),
  np.float64(54553.0),
  'Jalen Tolbert',
  ('2025090400-3606-092', np.int64(22), np.float64(10.168604603702207)),
  'right'),
 (np.float64(2025090400.0),
  np.float64(3606.0),
  np.float64(54594.0),
  'Jake Ferguson',
  ('2025090400-3606-096', np.int64(24), np.float64(14.38533328081175)),
  'right'),
 (np.float64(2025090400.0),
  np.float64(3266.0),
  np.float64(46118.0),
  'Dallas Goedert',
  ('2025090400-3266-130', np.int64(27), np.float64(39.23544180620854)),
  'left'),
 (np.float64(2025090400.0),
  np.float64(3266.0),
  np.float64(47834.0),
  'A.J. Brown',
  ('2025090400-3266-127', np.int64(25), np.float64(19.09374941108092)),
  'left'),
 (np.float64(2025090400.0),
  np.float64(3266.0),
  np.float64(52470.0),
  'AJ Dillon',
  ('2025090400-3266-170', np.int64(65), np.float64(16.944206758689973)),
  'left'),
 (np.float64(2025090400.0),
  np.float64(3266.0),
  np.float64(53439.0),
  'DeVonta Smith',
  ('2025090400-3266-150', np.int64(47), np.float64(35.556415457467466)),
  'left'),
 (np.float64(2025090400.0),
  np.float64(3266.0),
  np.float64(54481.0),
  'Jahan Dotson',
  ('2025090400-3266-137', np.int64(32), np.float64(15.981754553011285)),
  'left'),
 (np.float64(2025090400.0),
  np.float64(2609.0),
  np.float64(52425.0),
  'CeeDee Lamb',
  ('2025090400-2609-172', np.int64(21), np.float64(19.098464434776588)),
  'left'),
 (np.float64(2025090400.0),
  np.float64(2609.0),
  np.float64(53464.0),
  'Javonte Williams',
  [],
  'left'),
 (np.float64(2025090400.0),
  np.float64(2609.0),
  np.float64(54517.0),
  'George Pickens',
  ('2025090400-2609-170', np.int64(19), np.float64(16.967995713319624)),
  'left'),
 (np.float64(2025090400.0),
  np.float64(2609.0),
  np.float64(54553.0),
  'Jalen Tolbert',
  ('2025090400-2609-169', np.int64(15), np.float64(8.910541294977804)),
  'left'),
 (np.float64(2025090400.0),
  np.float64(2609.0),
  np.float64(54594.0),
  'Jake Ferguson',
  ('2025090400-2609-172', np.int64(22), np.float64(8.100014211085522)),
  'left'),
 (np.float64(2025090400.0),
  np.float64(2498.0),
  np.float64(52425.0),
  'CeeDee Lamb',
  ('2025090400-2498-159', np.int64(21), np.float64(20.987780348202023)),
  'left'),
 (np.float64(2025090400.0),
  np.float64(2498.0),
  np.float64(53464.0),
  'Javonte Williams',
  [],
  'left'),
 (np.float64(2025090400.0),
  np.float64(2498.0),
  np.float64(54517.0),
  'George Pickens',
  [],
  'left'),
 (np.float64(2025090400.0),
  np.float64(2498.0),
  np.float64(55923.0),
  'Luke Schoonmaker',
  ('2025090400-2498-150', np.int64(11), np.float64(14.976338231828493)),
  'left'),
 (np.float64(2025090400.0),
  np.float64(2498.0),
  np.float64(57649.0),
  'Brevyn Spann-Ford',
  [],
  'left'),
 (np.float64(2025090400.0),
  np.float64(2867.0),
  np.float64(52425.0),
  'CeeDee Lamb',
  ('2025090400-2867-207', np.int64(27), np.float64(18.9525715071766)),
  'left'),
 (np.float64(2025090400.0),
  np.float64(2867.0),
  np.float64(53117.0),
  'KaVontae Turpin',
  [],
  'left'),
 (np.float64(2025090400.0),
  np.float64(2867.0),
  np.float64(54517.0),
  'George Pickens',
  [],
  'left'),
 (np.float64(2025090400.0),
  np.float64(2867.0),
  np.float64(54594.0),
  'Jake Ferguson',
  ('2025090400-2867-198', np.int64(17), np.float64(17.585233387459937)),
  'left'),
 (np.float64(2025090400.0),
  np.float64(1647.0),
  np.float64(46071.0),
  'Saquon Barkley',
  ('2025090400-1647-242', np.int64(47), np.float64(12.953484988276223)),
  'right'),
 (np.float64(2025090400.0),
  np.float64(1647.0),
  np.float64(46118.0),
  'Dallas Goedert',
  ('2025090400-1647-223', np.int64(29), np.float64(15.369537005263311)),
  'right'),
 (np.float64(2025090400.0),
  np.float64(1647.0),
  np.float64(47834.0),
  'A.J. Brown',
  ('2025090400-1647-228', np.int64(35), np.float64(18.911717675831483)),
  'right'),
 (np.float64(2025090400.0),
  np.float64(1647.0),
  np.float64(53439.0),
  'DeVonta Smith',
  ('2025090400-1647-238', np.int64(46), np.float64(11.858228751147202)),
  'right'),
 (np.float64(2025090400.0),
  np.float64(1647.0),
  np.float64(54481.0),
  'Jahan Dotson',
  [],
  'right'),
 (np.float64(2025090400.0),
  np.float64(1043.0),
  np.float64(46071.0),
  'Saquon Barkley',
  [],
  'right'),
 (np.float64(2025090400.0),
  np.float64(1043.0),
  np.float64(46118.0),
  'Dallas Goedert',
  ('2025090400-1043-223', np.int64(26), np.float64(40.797087014412554)),
  'right'),
 (np.float64(2025090400.0),
  np.float64(1043.0),
  np.float64(47834.0),
  'A.J. Brown',
  [],
  'right'),
 (np.float64(2025090400.0),
  np.float64(1043.0),
  np.float64(53439.0),
  'DeVonta Smith',
  ('2025090400-1043-227', np.int64(28), np.float64(11.416344737177468)),
  'right'),
 (np.float64(2025090400.0),
  np.float64(1043.0),
  np.float64(54481.0),
  'Jahan Dotson',
  ('2025090400-1043-233', np.int64(35), np.float64(20.102278299793454)),
  'right'),
 (np.float64(2025090400.0),
  np.float64(1725.0),
  np.float64(46071.0),
  'Saquon Barkley',
  ('2025090400-1725-235', np.int64(26), np.float64(23.741615076045527)),
  'right'),
 (np.float64(2025090400.0),
  np.float64(1725.0),
  np.float64(46118.0),
  'Dallas Goedert',
  ('2025090400-1725-232', np.int64(23), np.float64(15.155449806515435)),
  'right'),
 (np.float64(2025090400.0),
  np.float64(1725.0),
  np.float64(47834.0),
  'A.J. Brown',
  ('2025090400-1725-226', np.int64(14), np.float64(11.794243454509214)),
  'right'),
 (np.float64(2025090400.0),
  np.float64(1725.0),
  np.float64(53439.0),
  'DeVonta Smith',
  ('2025090400-1725-236', np.int64(27), np.float64(13.588705814880797)),
  'right'),
 (np.float64(2025090400.0),
  np.float64(1725.0),
  np.float64(54481.0),
  'Jahan Dotson',
  ('2025090400-1725-224', np.int64(12), np.float64(24.85975588267349)),
  'right'),
 (np.float64(2025090400.0),
  np.float64(3219.0),
  np.float64(46071.0),
  'Saquon Barkley',
  [],
  'left'),
 (np.float64(2025090400.0),
  np.float64(3219.0),
  np.float64(47834.0),
  'A.J. Brown',
  [],
  'left'),
 (np.float64(2025090400.0),
  np.float64(3219.0),
  np.float64(53439.0),
  'DeVonta Smith',
  [],
  'left'),
 (np.float64(2025090400.0),
  np.float64(3219.0),
  np.float64(53556.0),
  'Kylen Granson',
  ('2025090400-3219-115', np.int64(28), np.float64(13.474264383498564)),
  'left'),
 (np.float64(2025090400.0),
  np.float64(3219.0),
  np.float64(54663.0),
  'Grant Calcaterra',
  ('2025090400-3219-112', np.int64(25), np.float64(10.925048961152243)),
  'left'),
 (np.float64(2025090400.0),
  np.float64(3027.0),
  np.float64(46071.0),
  'Saquon Barkley',
  ('2025090400-3027-236', np.int64(41), np.float64(9.564811712092904)),
  'left'),
 (np.float64(2025090400.0),
  np.float64(3027.0),
  np.float64(46118.0),
  'Dallas Goedert',
  ('2025090400-3027-215', np.int64(20), np.float64(11.035458963679048)),
  'left'),
 (np.float64(2025090400.0),
  np.float64(3027.0),
  np.float64(47834.0),
  'A.J. Brown',
  ('2025090400-3027-211', np.int64(13), np.float64(19.143571176761043)),
  'left'),
 (np.float64(2025090400.0),
  np.float64(3027.0),
  np.float64(53439.0),
  'DeVonta Smith',
  ('2025090400-3027-218', np.int64(23), np.float64(8.101908711070053)),
  'left'),
 (np.float64(2025090400.0),
  np.float64(3027.0),
  np.float64(54663.0),
  'Grant Calcaterra',
  ('2025090400-3027-214', np.int64(18), np.float64(12.93007048827215)),
  'left'),
 (np.float64(2025090400.0),
  np.float64(1326.0),
  np.float64(52425.0),
  'CeeDee Lamb',
  ('2025090400-1326-165', np.int64(28), np.float64(10.611578821146935)),
  'left'),
 (np.float64(2025090400.0),
  np.float64(1326.0),
  np.float64(53117.0),
  'KaVontae Turpin',
  [],
  'left'),
 (np.float64(2025090400.0),
  np.float64(1326.0),
  np.float64(54517.0),
  'George Pickens',
  ('2025090400-1326-165', np.int64(27), np.float64(18.988716214494445)),
  'left'),
 (np.float64(2025090400.0),
  np.float64(1326.0),
  np.float64(54594.0),
  'Jake Ferguson',
  [],
  'left'),
 (np.float64(2025090400.0),
  np.float64(1093.0),
  np.float64(46071.0),
  'Saquon Barkley',
  ('2025090400-1093-215', np.int64(7), np.float64(5.253247537442881)),
  'right'),
 (np.float64(2025090400.0),
  np.float64(1093.0),
  np.float64(46118.0),
  'Dallas Goedert',
  ('2025090400-1093-245', np.int64(40), np.float64(14.902024851432078)),
  'right'),
 (np.float64(2025090400.0),
  np.float64(1093.0),
  np.float64(53439.0),
  'DeVonta Smith',
  ('2025090400-1093-233', np.int64(26), np.float64(15.320858525741258)),
  'right'),
 (np.float64(2025090400.0),
  np.float64(1093.0),
  np.float64(53556.0),
  'Kylen Granson',
  ('2025090400-1093-220', np.int64(12), np.float64(28.75700357629681)),
  'right'),
 (np.float64(2025090400.0),
  np.float64(141.0),
  np.float64(52425.0),
  'CeeDee Lamb',
  [],
  'right'),
 (np.float64(2025090400.0),
  np.float64(141.0),
  np.float64(53117.0),
  'KaVontae Turpin',
  [],
  'right'),
 (np.float64(2025090400.0),
  np.float64(141.0),
  np.float64(54517.0),
  'George Pickens',
  ('2025090400-141-176', np.int64(21), np.float64(10.72388652736187)),
  'right'),
 (np.float64(2025090400.0),
  np.float64(141.0),
  np.float64(55923.0),
  'Luke Schoonmaker',
  [],
  'right'),
 (np.float64(2025090400.0),
  np.float64(778.0),
  np.float64(47836.0),
  'Miles Sanders',
  [],
  'right'),
 (np.float64(2025090400.0),
  np.float64(778.0),
  np.float64(53117.0),
  'KaVontae Turpin',

In [57]:
records = []

for game_id, gsis_play_id, nfl_id, display_name, final_break_frame, play_direction in break_frames_final:
    player_df = tracking_data[
        (tracking_data['game_id'] == game_id) &
        (tracking_data['gsis_play_id'] == gsis_play_id) &
        (tracking_data['nfl_id'] == nfl_id)
    ].sort_values('frame_id')

    if player_df.empty:
        continue

    route_type = player_df['route'].iloc[0]

    # final_break_frame is either a tuple (frame_id, peak_idx, total_turn)
    # or an empty list (no break found)
    if final_break_frame and isinstance(final_break_frame, tuple):
        direction_mult = 1 if play_direction == 'right' else -1
        break_frame_id = final_break_frame[0]
        route_break_depth = round(
            direction_mult * (
                player_df.loc[player_df['frame_id'] == break_frame_id, 'x'].values[0]
                - player_df['x_ball_at_snap'].values[0]
            )
        )
    else:
        break_frame_id = None
        route_break_depth = None

    records.append({
        'game_id': int(game_id),
        'gsis_play_id': int(gsis_play_id),
        'nfl_id': int(nfl_id),
        'display_name': display_name,
        'route': route_type,
        'route_break_frame': break_frame_id,
        'route_break_depth': int(route_break_depth) if route_break_depth is not None else None
    })

tracking_data_play = pd.DataFrame(records)
tracking_data_play.head(50)

       game_id  gsis_play_id  nfl_id      display_name   route    route_break_frame  route_break_depth
0   2025090400          1933   52425       CeeDee Lamb      GO                  NaN                NaN
1   2025090400          1933   53117   KaVontae Turpin    FLAT  2025090400-1933-199                3.0
2   2025090400          1933   53464  Javonte Williams     OUT  2025090400-1933-202                2.0
3   2025090400          1933   54517    George Pickens   HITCH  2025090400-1933-201               10.0
4   2025090400          1933   54594     Jake Ferguson     OUT  2025090400-1933-197                4.0
5   2025090400          2164   46071    Saquon Barkley    FLAT  2025090400-2164-150               -4.0
6   2025090400          2164   46118    Dallas Goedert    FLAT  2025090400-2164-163               -1.0
7   2025090400          2164   47834        A.J. Brown   CROSS  2025090400-2164-155                4.0
8   2025090400          2164   53439     DeVonta Smith     OUT  2025090400-2164-158                2.0
9   2025090400          2164   54663  Grant Calcaterra     OUT  2025090400-2164-170               13.0
10  2025090400          3451   52425       CeeDee Lamb  CORNER  2025090400-3451-235               19.0
11  2025090400          3451   53117   KaVontae Turpin   CROSS  2025090400-3451-236               16.0
12  2025090400          3451   53464  Javonte Williams    FLAT  2025090400-3451-209               -2.0
13  2025090400          3451   54517    George Pickens      IN  2025090400-3451-233               15.0
14  2025090400          3451   54594     Jake Ferguson   CROSS  2025090400-3451-245                4.0
15  2025090400          3643   52425       CeeDee Lamb   HITCH  2025090400-3643-074               14.0
16  2025090400          3643   53464  Javonte Williams   ANGLE  2025090400-3643-072                3.0
17  2025090400          3643   54517    George Pickens     OUT  2025090400-3643-070               13.0
18  2025090400          3643   54553     Jalen Tolbert   HITCH  2025090400-3643-066                8.0
19  2025090400          3643   54594     Jake Ferguson     OUT  2025090400-3643-067                8.0
20  2025090400          3724   53117   KaVontae Turpin   HITCH  2025090400-3724-134                7.0
21  2025090400          3724   53464  Javonte Williams   ANGLE                  NaN                NaN
22  2025090400          3724   54517    George Pickens      IN  2025090400-3724-134               13.0
23  2025090400          3724   54553     Jalen Tolbert    POST  2025090400-3724-135               15.0
24  2025090400          3724   55923  Luke Schoonmaker  CORNER  2025090400-3724-137               13.0
25  2025090400          3671   52425       CeeDee Lamb      IN  2025090400-3671-176               10.0
26  2025090400          3671   53464  Javonte Williams    FLAT                  NaN                NaN
27  2025090400          3671   54517    George Pickens     OUT  2025090400-3671-180               15.0
28  2025090400          3671   54553     Jalen Tolbert     OUT  2025090400-3671-166                3.0
29  2025090400          3671   54594     Jake Ferguson   HITCH  2025090400-3671-178                5.0
30  2025090400          3701   52425       CeeDee Lamb      GO                  NaN                NaN
31  2025090400          3701   53464  Javonte Williams     OUT  2025090400-3701-080                7.0
32  2025090400          3701   54517    George Pickens   HITCH  2025090400-3701-052                7.0
33  2025090400          3701   54553     Jalen Tolbert      GO                  NaN                NaN
34  2025090400          3701   54594     Jake Ferguson      GO                  NaN                NaN
35  2025090400          1958   52425       CeeDee Lamb      GO                  NaN                NaN
36  2025090400          1958   53464  Javonte Williams   ANGLE  2025090400-1958-087                2.0
37  2025090400          1958   54517    George Pickens     OUT  2025090400-1958-084               17.0
38  2025090400          1958   54553     Jalen Tolbert    FLAT  2025090400-1958-072                1.0
39  2025090400          1958   54594     Jake Ferguson    FLAT  2025090400-1958-062               -2.0
40  2025090400          1695   46071    Saquon Barkley    FLAT                  NaN                NaN
41  2025090400          1695   46118    Dallas Goedert  CORNER  2025090400-1695-194               13.0
42  2025090400          1695   47834        A.J. Brown      IN  2025090400-1695-185                5.0
43  2025090400          1695   53439     DeVonta Smith      GO                  NaN                NaN
44  2025090400          1695   54481      Jahan Dotson   HITCH  2025090400-1695-193               11.0
45  2025090400           330   46071    Saquon Barkley    FLAT                  NaN                NaN
46  2025090400           330   46118    Dallas Goedert   CROSS   2025090400-330-218                1.0
47  2025090400           330   47834        A.J. Brown    POST   2025090400-330-230               13.0
48  2025090400           330   53439     DeVonta Smith      IN   2025090400-330-228                8.0
49  2025090400           330   54481      Jahan Dotson    FLAT                  NaN                NaN

In [58]:
tracking_data_play.to_csv('data/tracking_data_play_2025090400.csv', index=False)

In [59]:
# play_3783 = tracking_data[
#     (tracking_data['game_id'] == 2025121408) &
#     (tracking_data['gsis_play_id'] == 3783) &
#     (tracking_data['nfl_id'] == 46109)
# ]
# play_3783

# submit_frames = play_3783.loc[play_3783['event'].isin(end_events)][['event', 'frame_id']]

# submit_frames

# # if submit_frames.empty:
# #     submit_frames = player_df.loc[player_df['event'] == 'play_submit', 'time']

# # # skip if this player/play doesn't have both events
# # if snap_frames.empty or submit_frames.empty:
# #     continue

# # snap_frame = snap_frames.iloc[0]
# # submit_frame = submit_frames.iloc[0]